source_id: "Id"
name: "Opgavenavn"
planned_start: "Startdato"
planned_finish: "Slutdato"
duration: "Varighed"
percent_complete: "% arbejde færdigt"
predecessors: "Foregående opgaver"
successors: "Efterfølgende opgaver"
discipline: "Ansvarlig"
area: "omr."
floor: "Etage"
remarks: "bemærkn."
wbs_code: "TBS"
